#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the FT232H for the depth sensor."
echo ""

sudo cp `rospack find depth_node_py`/misc/57-ft232h.rules /etc/udev/rules.d


echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart
